# Generated by Django 3.0.2 on 2020-04-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20200405_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_registration',
            name='designation',
            field=models.CharField(default='Software Developer', max_length=50),
            preserve_default=False,
        ),
    ]
