# Generated by Django 3.0.2 on 2020-04-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_registration_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_registration',
            name='selection',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher_registration',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
