# Generated by Django 3.0.2 on 2020-04-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20200406_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_registration',
            name='about',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_registration',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_registration',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_registration',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_registration',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='teacher'),
        ),
        migrations.AlterField(
            model_name='teacher_registration',
            name='selection',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher_registration',
            name='work_exp',
            field=models.IntegerField(null=True),
        ),
    ]
