# Generated by Django 3.0.2 on 2020-04-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20200406_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_registration',
            name='id',
        ),
        migrations.AlterField(
            model_name='teacher_registration',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
