# Generated by Django 3.0.2 on 2020-04-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_auto_20200406_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_registration',
            name='profile_photo',
            field=models.ImageField(default=0, upload_to='teacher/'),
            preserve_default=False,
        ),
    ]
