# Generated by Django 3.0.2 on 2020-04-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_auto_20200406_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_registration',
            name='profile_photo',
            field=models.ImageField(upload_to='teacher'),
        ),
    ]
