# Generated by Django 3.0.2 on 2020-04-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50, null=True)),
                ('cdiscription', models.CharField(max_length=50, null=True)),
                ('cphoto', models.ImageField(upload_to='course')),
                ('temail', models.EmailField(max_length=20, null=True)),
                ('tpassword', models.CharField(max_length=50, null=True)),
                ('ccategory', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
