# Generated by Django 3.0.2 on 2020-04-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_registration',
            name='teacher_designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course_registration',
            name='teacher_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course_registration',
            name='teacher_profile_photo',
            field=models.ImageField(default=0, upload_to='teacher'),
            preserve_default=False,
        ),
    ]
