# Generated by Django 3.0.2 on 2020-04-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200407_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('cphoto', models.ImageField(upload_to='course')),
                ('category', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
