# Generated by Django 3.0.2 on 2020-04-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_count',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course_count',
            name='cphoto',
        ),
        migrations.RemoveField(
            model_name='course_count',
            name='name',
        ),
        migrations.AddField(
            model_name='course_count',
            name='banking',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course_count',
            name='civil_services',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course_count',
            name='social_media',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course_count',
            name='soft_dev',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course_count',
            name='web_dev',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
