# Generated by Django 3.0.2 on 2020-04-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200407_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_registration',
            name='cfile',
            field=models.FileField(default=0, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
